### ISSUE TITLE
Static / Constant properties and Enums not supported as parameters in method calls

### ISSUE THREAD

**Issue by JeffyW** [StefH/System.Linq.Dynamic.Core#144]
I'm looking to use `System.Linq.Dynamic.Core` as a way of parsing dynamic lambda expressions over known entity types as a way of serializing "expressions".

One of the simple things we'd be looking to support is case-insensitive comparison of strings.  While one way to support this would be to force an expression like `P.String.ToLower() == "string"`, it would be nice if we could support `P.String.Equals("String", System.StringComparison.OrdinalIgnoreCase)`.  Unfortunately, the parser currently confuses the namespace for a property on P because of the optimization allowing omission of the parameter identifier.

This is the same root cause for why types have to be explicitly handled via KeywordsHelper.

# Repro
```
public class Foo
{
    public string String;
}
```
```
var foo = new Foo { String = "HI" };
var expression = "P.String.Equals(\"hi\", System.StringComparison.OrdinalIgnoreCase)";
ParameterExpression p = Expression.Parameter(foo.GetType(), "P");
LambdaExpression lambdaExpression = DynamicExpressionParser.ParseLambda(new[] { p }, typeof(bool), expression);
var result = lambdaExpression.Compile().DynamicInvoke(foo);
```
# Expected
`result == true`
# Actual
```
No property or field 'System' exists in type 'Foo'
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArguments()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArgumentList()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
```

**Comment by KentRollins** [comment]
You can do what you are asking for with at least v1.0.8.2.  You need to tweak your expression slightly and make the StringComparison type available to the expression parser so it knows how to handle it.

First, change your expression by dropping the "System.".  This is throwing the parser off and might be considered a bug by itself.
`"P.String.Equals(\"hi\", StringComparison.OrdinalIgnoreCase)"`

The next part is a little more complicated but it allows you to call static methods and use enumerations.  You have to create a class that implements `IDynamicLinkCustomTypeProvider`.  This interface returns a Set of types.

Add the enumeration to the Set:
`myTypeCollection.Add(typeof(StringComparison));`

Then when you compile the expression, use the overload that allows for a ParserConfig:
```
ParsingConfig cfg = new ParsingConfig();
cfg.CustomTypeProvider = ifTypeProvider;  // myTypeCollection
LambdaExpression expr = DynamicExpressionParser.ParseLambda(cfg, lstParameterExprs.ToArray(), typeof(T), ExpressionString);
```

I had to do this to use System.Math which is mostly static methods.  I built on an answer on [StackOverflow.com](https://stackoverflow.com/a/34301514/1583763).

**Comment by StefH** [comment]
Linked to https://github.com/StefH/System.Linq.Dynamic.Core/issues/128

**Comment by StefH** [comment]
@JeffyW I'm closing this one. Take also a look at the https://github.com/StefH/System.Linq.Dynamic.Core/issues/128.

If you still have questions, open a new issue.
