### ISSUE TITLE
Compatibility with System.Linq.Dynamic.Library 

### ISSUE THREAD

**Issue by jwperez1** [StefH/System.Linq.Dynamic.Core#35]
Is this backwards compatible with System.Linq.Dynamic.Library  by Nathan Arnott?  That lib seems to have disappeared and I am looking for a way to migrate my code.  I think I see you started with a fork from there.

**Comment by StefH** [comment]
This library is indeed a fork from the deleted library from Nathan.

It should be compatible, except for some namespaces.

**Comment by jwperez1** [comment]
Awesome.  I pulled it using nugit and the only thing I had to do was change the using to have the correct namespace and it builds perfectly.  I get the error below when I run the app immediately after building:

+		[1]	{"Could not load file or assembly 'Remotion.Data.Linq, Version=1.13.52.2, Culture=neutral, PublicKeyToken=0669cf0452175907' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Remotion.Data.Linq, Version=1.13.52.2, Culture=neutral, PublicKeyToken=0669cf0452175907"}	System.Exception {System.IO.FileLoadException}

The odd thing is, if I run the app again (without building it), it works without an error.  The error occurs the first time I make a call to the dynamic linq api.  This is the stacktrace:

   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.Linq.Dynamic.Core.CustomTypeProviders.DefaultDynamicLinqCustomTypeProvider.<>c.<FindTypesMarkedWithAttribute>b__3_1(Assembly x)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Dynamic.Core.CustomTypeProviders.DefaultDynamicLinqCustomTypeProvider.GetCustomTypes()
   at System.Linq.Dynamic.Core.ExpressionParser.CreateKeywords()
   at System.Linq.Dynamic.Core.ExpressionParser..ctor(ParameterExpression[] parameters, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Boolean createParameterCtor, Type itType, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, String predicate, Object[] args)
   at DashboardDemo1.Model.Criteria.Filter.FilterIt[U](SearchCriteria criteria, IQueryable`1 query)

This happened for the first time this morning (I have had the app in prod since February).  I was hoping migrating to your api would fix it but it did not.  Do you have any idea what is causing this?

**Comment by StefH** [comment]
Which dotnet framework do you use ?

And regarding this CustomTypeProvider error, it could be that some small business logic is different when loading external libraries.

**Comment by jwperez1** [comment]
I use 4.5.1

**Comment by jogibear9988** [comment]
When we look in the code from Nathan: (he deleted his branch) https://github.com/jogibear9988/System.Linq.Dynamic/blob/master/Src/System.Linq.Dynamic/DynamicLinqTypeProvider.cs
we use AppDomain.CurrentDomain.GetAssemblies(); the same in https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DefaultAssemblyHelper.cs

The difference is this line: assemblies = assemblies.Where(x => !x.IsDynamic).ToArray();

But do we need that array?

**Comment by jogibear9988** [comment]
Maybe also we could make the default "CustomTypeProvider" exception friendly. 
See: https://github.com/StefH/System.Linq.Dynamic.Core/pull/39

**Comment by jogibear9988** [comment]
i think this could now be closed?

**Comment by StefH** [comment]
@jwperez1 ; can you please verify ?

**Comment by StefH** [comment]
Closing issue.

**Comment by mayankgaur** [comment]
Is it resolved I am also facing same issue?

**Comment by jogibear9988** [comment]
What issue?

**Comment by mayankgaur** [comment]
@jogibear9988 I am having below issue

System.IO.FileLoadException: 'Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.0.17.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
