### ISSUE TITLE
Why I'm not able to group by another table?

### ISSUE THREAD

**Issue by rochapablo** [StefH/System.Linq.Dynamic.Core#374]
```
.GroupBy("new (it.mytable2.column)")
.Select("new (it.Key.mytable2.column, it.Sum(amount1) as amount1, it.Sum(amount2) as amount2)", "T", StringComparison.OrdinalIgnoreCase)
```

```
"Expression is missing an 'as' clause"
```

If I try to add alias:

```
.GroupBy("new (it.mytable2.column)")
.Select("new (it.Key.mytable2.column as mycolumn, it.Sum(amount1) as amount1, it.Sum(amount2) as amount2)", "T", StringComparison.OrdinalIgnoreCase)
```

```
"Specified argument was out of the range of valid values. (Parameter 'index')"
```

It should be working like this

```
var data = Db.mytable
.GroupBy(x => new { x.mytable2.column })
.Select(x => new { x.mytable2.column, Total = x.Sum(y => y.Total) });
```

https://stackoverflow.com/questions/61461191/why-im-not-able-to-group-by-another-table

**Comment by StefH** [comment]
Just use 
``` c#
var rDynamic = data.GroupBy("new(col1)").Select("new (Key, Sum(col3) as Total)");
```

![image](https://user-images.githubusercontent.com/249938/80389067-ec63c200-88aa-11ea-9681-5c403ac86cbc.png)

**Comment by mccollumni** [comment]
I tried to something similar, and it's not recognizing "Sum" as a function:
```
_context.Orders
                    .GroupBy("new(Customer.FirstName)")
                    .Select("new (Key, Sum(Customer.FirstName) as Sum)")
                    .ToDynamicList();
```

The error:
```
Unexpected error No applicable aggregate method 'Sum(String)' exists    at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAggregate(Expression instance, Type elementType, String methodName, Int32 errorPos, Boolean isQueryable)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance)
```
